#!/usr/bin/env python3
"""
Read mock Damiao motor feedback frames from can0/can1 for OpenArm Task 2.

This script reads CAN-FD frames generated by mock_damiao_stream.py and
converts them into normalized joint-state JSONL records.

Expected mock payload layout:
    <QBBBBfff

    Q    uint64 timestamp_ns
    B    uint8  arm_index
    B    uint8  joint_index
    B    uint8  sender_can_id
    B    uint8  receiver_can_id
    f    float32 position_rad
    f    float32 velocity_rad_s
    f    float32 torque_nm

Expected arbitration IDs:
    0x11-0x18 on each CAN interface.
"""

import argparse
import json
import queue
import signal
import struct
import threading
import time
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional

import can


PAYLOAD_FORMAT = "<QBBBBfff"
PAYLOAD_SIZE = struct.calcsize(PAYLOAD_FORMAT)

VALID_RECEIVER_CAN_IDS = set(range(0x11, 0x19))

ARM_NAMES = {
    0: "left",
    1: "right",
}

INTERFACE_TO_ARM_NAME = {
    "can0": "left",
    "can1": "right",
}

running = True


@dataclass
class JointState:
    host_received_ns: int
    sensor_timestamp_ns: int
    interface: str
    arm_name: str
    arm_index: int
    joint_name: str
    joint_index: int
    sender_can_id: int
    receiver_can_id: int
    arbitration_id: int
    position_rad: float
    velocity_rad_s: float
    torque_nm: float


def handle_signal(signum, frame):
    global running
    running = False


def joint_name_from_index(joint_index: int) -> str:
    """
    Convert joint index to readable joint name.
    """
    if joint_index == 8:
        return "J8_gripper"
    return f"J{joint_index}"


def parse_feedback_frame(interface: str, msg: can.Message) -> Optional[JointState]:
    """
    Parse one CAN-FD feedback frame into a normalized JointState.

    Returns None if:
    - the message is not CAN-FD
    - the arbitration ID is outside the expected mock feedback range
    - the payload length is not the expected 24 bytes
    - the metadata inside the payload is inconsistent
    """
    if not msg.is_fd:
        return None

    if msg.arbitration_id not in VALID_RECEIVER_CAN_IDS:
        return None

    if len(msg.data) != PAYLOAD_SIZE:
        return None

    (
        sensor_timestamp_ns,
        arm_index,
        joint_index,
        sender_can_id,
        receiver_can_id,
        position_rad,
        velocity_rad_s,
        torque_nm,
    ) = struct.unpack(PAYLOAD_FORMAT, msg.data)

    if joint_index < 1 or joint_index > 8:
        return None

    if sender_can_id < 0x01 or sender_can_id > 0x08:
        return None

    if receiver_can_id < 0x11 or receiver_can_id > 0x18:
        return None

    if receiver_can_id != msg.arbitration_id:
        return None

    expected_receiver_can_id = 0x10 + joint_index
    if receiver_can_id != expected_receiver_can_id:
        return None

    expected_sender_can_id = joint_index
    if sender_can_id != expected_sender_can_id:
        return None

    arm_name = ARM_NAMES.get(arm_index, f"arm_{arm_index}")

    # Extra consistency check: in this mock, can0 is left and can1 is right.
    expected_arm_name = INTERFACE_TO_ARM_NAME.get(interface)
    if expected_arm_name is not None and arm_name != expected_arm_name:
        return None

    return JointState(
        host_received_ns=time.time_ns(),
        sensor_timestamp_ns=int(sensor_timestamp_ns),
        interface=interface,
        arm_name=arm_name,
        arm_index=int(arm_index),
        joint_name=joint_name_from_index(int(joint_index)),
        joint_index=int(joint_index),
        sender_can_id=int(sender_can_id),
        receiver_can_id=int(receiver_can_id),
        arbitration_id=int(msg.arbitration_id),
        position_rad=float(position_rad),
        velocity_rad_s=float(velocity_rad_s),
        torque_nm=float(torque_nm),
    )


def reader_thread(interface: str, output_queue: queue.Queue):
    """
    Continuously read CAN-FD frames from one SocketCAN interface.

    Parsed JointState objects are pushed into output_queue.
    """
    bus = can.Bus(interface="socketcan", channel=interface, fd=True)

    try:
        while running:
            msg = bus.recv(timeout=0.1)
            if msg is None:
                continue

            state = parse_feedback_frame(interface, msg)
            if state is not None:
                output_queue.put(state)

    finally:
        bus.shutdown()


def main():
    parser = argparse.ArgumentParser(
        description="Read mock OpenArm joint states from CAN-FD frames."
    )
    parser.add_argument(
        "--duration-s",
        type=float,
        default=10.0,
        help="How long to read before exiting. Default: 10 seconds.",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="data/joint_states_mock.jsonl",
        help="Output JSONL path.",
    )
    parser.add_argument(
        "--interfaces",
        nargs="+",
        default=["can0", "can1"],
        help="SocketCAN interfaces to read. Default: can0 can1.",
    )
    parser.add_argument(
        "--print-every",
        type=int,
        default=200,
        help="Print every N parsed frames after the first few. Default: 200.",
    )
    args = parser.parse_args()

    if args.duration_s <= 0:
        raise ValueError("--duration-s must be positive")

    signal.signal(signal.SIGINT, handle_signal)
    signal.signal(signal.SIGTERM, handle_signal)

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    output_queue: queue.Queue = queue.Queue()

    threads = [
        threading.Thread(
            target=reader_thread,
            args=(interface, output_queue),
            daemon=True,
        )
        for interface in args.interfaces
    ]

    for thread in threads:
        thread.start()

    print("[MOCK MODE] Reading OpenArm-style joint states from CAN-FD")
    print(f"[MOCK MODE] interfaces={args.interfaces}")
    print(f"[MOCK MODE] payload_format={PAYLOAD_FORMAT}")
    print(f"[MOCK MODE] payload_size={PAYLOAD_SIZE} bytes")
    print(f"[MOCK MODE] output={output_path}")

    start_time = time.monotonic()
    parsed_count = 0

    per_interface_count = {interface: 0 for interface in args.interfaces}
    per_arm_count = {}

    with output_path.open("w", encoding="utf-8") as f:
        while running and time.monotonic() - start_time < args.duration_s:
            try:
                state = output_queue.get(timeout=0.2)
            except queue.Empty:
                continue

            record = asdict(state)
            f.write(json.dumps(record) + "\n")
            f.flush()

            parsed_count += 1
            per_interface_count[state.interface] = per_interface_count.get(state.interface, 0) + 1
            per_arm_count[state.arm_name] = per_arm_count.get(state.arm_name, 0) + 1

            if parsed_count <= 8 or parsed_count % args.print_every == 0:
                print(json.dumps(record, indent=2))

    print()
    print("[MOCK MODE] Finished reading joint states.")
    print(f"[MOCK MODE] parsed_count={parsed_count}")
    print(f"[MOCK MODE] per_interface_count={per_interface_count}")
    print(f"[MOCK MODE] per_arm_count={per_arm_count}")
    print(f"[MOCK MODE] output_file={output_path}")


if __name__ == "__main__":
    main()